=== Andreea15B/Facultate_an_II/Semestru II/Tehnologii_Web/Laborator/Lab6/xml-dtd/cuprins/cuprins.dtd
<!-- DTD definind tipul de document 'cuprins' -->
<!ELEMENT cuprins	(coordonator?,capitol+)>
<!ELEMENT coordonator 	ANY>
<!ELEMENT capitol	(nume,autor*,descriere?)>
<!ELEMENT nume		(#PCDATA)>
<!ELEMENT autor		(#PCDATA)>
<!ELEMENT descriere	(#PCDATA)>

<!-- declararea unei entitati (cu utilizarea entitatilor predefinite) -->
<!ENTITY busaco "Sabin Buraga &lt;busaco@infoiasi.ro&gt;">

<!ATTLIST cuprins
      titlu 	CDATA		#REQUIRED
      editura	CDATA		#IMPLIED
      ANY 		(2004|2005|2007|2009)	"2007"
>      
<!ATTLIST capitol 
      numar 	CDATA 		#REQUIRED
>
<!ATTLIST autor 
      email 	CDATA 		#IMPLIED
>

=== Andreea15B/Facultate_an_II/Semestru II/Tehnologii_Web/Laborator/Lab6/xml-dtd/cuprins/cuprins-dtd.xml
<!DOCTYPE cuprins SYSTEM "cuprins.dtd">
<!-- pentru validare se foloseste un DTD extern -->
<cuprins titlu="Programarea in Web 2.0" editura="Polirom" an="2007">
  <coordonator>&busaco;</coordonator> 
  <capitol numar="1">
    <nume>Load-balancing in clustere Web</nume>
    <autor>Andrei Mihaila</autor>
    <descriere> Capitolul prezinta pas cu pas crearea unui modul Apache care sa
      functioneze intr-un cluster Web - scopul declarat al modulului este sa
      echilibreze incarcarea pe masinile care fac parte din cluster. Se incepe
      cu o scurta prezentare a serverului Apache si se continua cu discutarea
      unei parti a interfetei de programare a acestuia, ilustrindu-se
      chestiunile de interes pe baza unor exemple. Pe parcursul prezentarii se
      accentueaza latura practica a lucrurilor, astfel ca la sfirsit cititorul
      sa aiba la indemina un modul de Apache functional. </descriere>
  </capitol>
  <capitol numar="5">
    <nume>Aplicatii hibride - mashups</nume>
    <autor email="evalica@infoiasi.ro">Ecaterina Valica</autor>
    <descriere> Acest capitol prezinta detaliat termenul de mashup si
      instrumentele necesare crearii de aplicatii Web in acest stil. Sunt
      furnizate informatii privind accesul la informatii provenind din surse
      multiple pentru a fi integrate intr-o aplicatie Web hibrida. De asemenea,
      capitolul ilustreaza diverse exemple privind accesul la si refolosirea
      datelor oferite de servicii precum Google Maps, Yahoo! Search, Flickr sau
      Picasa prin intermediul unor tehnologii/paradigme ca XML-RPC, SOAP, REST
      sau AJAX. In plus, se discuta despre modalitati de creare a aplicatiilor
      mashup via diverse instrumente (e.g., Yahoo Pipes) si a componentelor Web
      de tip gadget sau mapplet. </descriere>
  </capitol>
</cuprins>
